# Generated by Django 5.0.6 on 2024-06-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerverse', '0002_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
