# Generated by Django 5.0.6 on 2024-06-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerverse', '0008_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
