# Generated by Django 5.0.6 on 2024-06-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerverse', '0010_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
